power: true
#必須: 落とし物を受け取るときに必要な手数料です
fee: 100
#必須: 落とした日から何日経つとフリマ入りするかの設定
marketday: 3
#ドロップアイテム一括消去設定
#Minecraftのデフォルトでドロップしたアイテムは300秒で消えます
clear:
  #必須: 何秒おきにアイテムを一括でクリアするか(300秒=5分) 0以下で停止
  sec: 300
  #警告を出す秒数のリスト(分は自動変換)
  warn:
    - 150
    - 60
    - 20
    - 5
    - 3
    - 2
    - 1
  #一括クリアから除外するワールド名リスト
  noclear:
    - 'noclearWorld'

#必須: データベース設定
db:
  sqlite: false
  mysql:
    host: localhost
    port: 3306
    user: root
    pass: password
    db: ilp_db